/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface WvLazyload {
    'componentName': string;
    'entityId': string;
    'nodeId': string;
    'nodeOptions': string;
    'pageId': string;
    'recordId': string;
    'siteRootUrl': string;
  }
  interface WvLazyloadAttributes extends StencilHTMLAttributes {
    'componentName'?: string;
    'entityId'?: string;
    'nodeId'?: string;
    'nodeOptions'?: string;
    'pageId'?: string;
    'recordId'?: string;
    'siteRootUrl'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WvLazyload': Components.WvLazyload;
  }

  interface StencilIntrinsicElements {
    'wv-lazyload': Components.WvLazyloadAttributes;
  }


  interface HTMLWvLazyloadElement extends Components.WvLazyload, HTMLStencilElement {}
  var HTMLWvLazyloadElement: {
    prototype: HTMLWvLazyloadElement;
    new (): HTMLWvLazyloadElement;
  };

  interface HTMLElementTagNameMap {
    'wv-lazyload': HTMLWvLazyloadElement
  }

  interface ElementTagNameMap {
    'wv-lazyload': HTMLWvLazyloadElement;
  }


}
