/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface WvRecurrenceTemplate {
    'changeTypeOptions': string;
    'endTypeOptions': string;
    'periodTypeOptions': string;
    'recurrenceTemplate': string;
    'templateDefault': string;
    'typeOptions': string;
  }
  interface WvRecurrenceTemplateAttributes extends StencilHTMLAttributes {
    'changeTypeOptions'?: string;
    'endTypeOptions'?: string;
    'periodTypeOptions'?: string;
    'recurrenceTemplate'?: string;
    'templateDefault'?: string;
    'typeOptions'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WvRecurrenceTemplate': Components.WvRecurrenceTemplate;
  }

  interface StencilIntrinsicElements {
    'wv-recurrence-template': Components.WvRecurrenceTemplateAttributes;
  }


  interface HTMLWvRecurrenceTemplateElement extends Components.WvRecurrenceTemplate, HTMLStencilElement {}
  var HTMLWvRecurrenceTemplateElement: {
    prototype: HTMLWvRecurrenceTemplateElement;
    new (): HTMLWvRecurrenceTemplateElement;
  };

  interface HTMLElementTagNameMap {
    'wv-recurrence-template': HTMLWvRecurrenceTemplateElement
  }

  interface ElementTagNameMap {
    'wv-recurrence-template': HTMLWvRecurrenceTemplateElement;
  }


}
