/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';

import '@stencil/redux';


export namespace Components {

  interface WvCreateModal {}
  interface WvCreateModalAttributes extends StencilHTMLAttributes {}

  interface WvHelpModal {}
  interface WvHelpModalAttributes extends StencilHTMLAttributes {}

  interface WvLoadingPane {}
  interface WvLoadingPaneAttributes extends StencilHTMLAttributes {}

  interface WvOptionsModal {}
  interface WvOptionsModalAttributes extends StencilHTMLAttributes {}

  interface WvPbInspector {}
  interface WvPbInspectorAttributes extends StencilHTMLAttributes {}

  interface WvPbManager {
    'libraryJson': string;
    'pageId': string;
    'pageNodesJson': string;
    'recordId': string;
    'siteRootUrl': string;
  }
  interface WvPbManagerAttributes extends StencilHTMLAttributes {
    'libraryJson'?: string;
    'pageId'?: string;
    'pageNodesJson'?: string;
    'recordId'?: string;
    'siteRootUrl'?: string;
  }

  interface WvPbNodeContainer {
    'containerId': string;
    'parentNodeId': string;
  }
  interface WvPbNodeContainerAttributes extends StencilHTMLAttributes {
    'containerId'?: string;
    'parentNodeId'?: string;
  }

  interface WvPbNode {
    'nodeId': string;
  }
  interface WvPbNodeAttributes extends StencilHTMLAttributes {
    'nodeId'?: string;
  }

  interface WvPbTreeNode {
    'level': number;
    'node': Object;
  }
  interface WvPbTreeNodeAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'node'?: Object;
  }

  interface WvPbTree {}
  interface WvPbTreeAttributes extends StencilHTMLAttributes {}

  interface WvShowHelp {
    'nodeId': string;
  }
  interface WvShowHelpAttributes extends StencilHTMLAttributes {
    'nodeId'?: string;
  }

  interface WvShowOptions {
    'nodeId': string;
  }
  interface WvShowOptionsAttributes extends StencilHTMLAttributes {
    'nodeId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WvCreateModal': Components.WvCreateModal;
    'WvHelpModal': Components.WvHelpModal;
    'WvLoadingPane': Components.WvLoadingPane;
    'WvOptionsModal': Components.WvOptionsModal;
    'WvPbInspector': Components.WvPbInspector;
    'WvPbManager': Components.WvPbManager;
    'WvPbNodeContainer': Components.WvPbNodeContainer;
    'WvPbNode': Components.WvPbNode;
    'WvPbTreeNode': Components.WvPbTreeNode;
    'WvPbTree': Components.WvPbTree;
    'WvShowHelp': Components.WvShowHelp;
    'WvShowOptions': Components.WvShowOptions;
  }

  interface StencilIntrinsicElements {
    'wv-create-modal': Components.WvCreateModalAttributes;
    'wv-help-modal': Components.WvHelpModalAttributes;
    'wv-loading-pane': Components.WvLoadingPaneAttributes;
    'wv-options-modal': Components.WvOptionsModalAttributes;
    'wv-pb-inspector': Components.WvPbInspectorAttributes;
    'wv-pb-manager': Components.WvPbManagerAttributes;
    'wv-pb-node-container': Components.WvPbNodeContainerAttributes;
    'wv-pb-node': Components.WvPbNodeAttributes;
    'wv-pb-tree-node': Components.WvPbTreeNodeAttributes;
    'wv-pb-tree': Components.WvPbTreeAttributes;
    'wv-show-help': Components.WvShowHelpAttributes;
    'wv-show-options': Components.WvShowOptionsAttributes;
  }


  interface HTMLWvCreateModalElement extends Components.WvCreateModal, HTMLStencilElement {}
  var HTMLWvCreateModalElement: {
    prototype: HTMLWvCreateModalElement;
    new (): HTMLWvCreateModalElement;
  };

  interface HTMLWvHelpModalElement extends Components.WvHelpModal, HTMLStencilElement {}
  var HTMLWvHelpModalElement: {
    prototype: HTMLWvHelpModalElement;
    new (): HTMLWvHelpModalElement;
  };

  interface HTMLWvLoadingPaneElement extends Components.WvLoadingPane, HTMLStencilElement {}
  var HTMLWvLoadingPaneElement: {
    prototype: HTMLWvLoadingPaneElement;
    new (): HTMLWvLoadingPaneElement;
  };

  interface HTMLWvOptionsModalElement extends Components.WvOptionsModal, HTMLStencilElement {}
  var HTMLWvOptionsModalElement: {
    prototype: HTMLWvOptionsModalElement;
    new (): HTMLWvOptionsModalElement;
  };

  interface HTMLWvPbInspectorElement extends Components.WvPbInspector, HTMLStencilElement {}
  var HTMLWvPbInspectorElement: {
    prototype: HTMLWvPbInspectorElement;
    new (): HTMLWvPbInspectorElement;
  };

  interface HTMLWvPbManagerElement extends Components.WvPbManager, HTMLStencilElement {}
  var HTMLWvPbManagerElement: {
    prototype: HTMLWvPbManagerElement;
    new (): HTMLWvPbManagerElement;
  };

  interface HTMLWvPbNodeContainerElement extends Components.WvPbNodeContainer, HTMLStencilElement {}
  var HTMLWvPbNodeContainerElement: {
    prototype: HTMLWvPbNodeContainerElement;
    new (): HTMLWvPbNodeContainerElement;
  };

  interface HTMLWvPbNodeElement extends Components.WvPbNode, HTMLStencilElement {}
  var HTMLWvPbNodeElement: {
    prototype: HTMLWvPbNodeElement;
    new (): HTMLWvPbNodeElement;
  };

  interface HTMLWvPbTreeNodeElement extends Components.WvPbTreeNode, HTMLStencilElement {}
  var HTMLWvPbTreeNodeElement: {
    prototype: HTMLWvPbTreeNodeElement;
    new (): HTMLWvPbTreeNodeElement;
  };

  interface HTMLWvPbTreeElement extends Components.WvPbTree, HTMLStencilElement {}
  var HTMLWvPbTreeElement: {
    prototype: HTMLWvPbTreeElement;
    new (): HTMLWvPbTreeElement;
  };

  interface HTMLWvShowHelpElement extends Components.WvShowHelp, HTMLStencilElement {}
  var HTMLWvShowHelpElement: {
    prototype: HTMLWvShowHelpElement;
    new (): HTMLWvShowHelpElement;
  };

  interface HTMLWvShowOptionsElement extends Components.WvShowOptions, HTMLStencilElement {}
  var HTMLWvShowOptionsElement: {
    prototype: HTMLWvShowOptionsElement;
    new (): HTMLWvShowOptionsElement;
  };

  interface HTMLElementTagNameMap {
    'wv-create-modal': HTMLWvCreateModalElement
    'wv-help-modal': HTMLWvHelpModalElement
    'wv-loading-pane': HTMLWvLoadingPaneElement
    'wv-options-modal': HTMLWvOptionsModalElement
    'wv-pb-inspector': HTMLWvPbInspectorElement
    'wv-pb-manager': HTMLWvPbManagerElement
    'wv-pb-node-container': HTMLWvPbNodeContainerElement
    'wv-pb-node': HTMLWvPbNodeElement
    'wv-pb-tree-node': HTMLWvPbTreeNodeElement
    'wv-pb-tree': HTMLWvPbTreeElement
    'wv-show-help': HTMLWvShowHelpElement
    'wv-show-options': HTMLWvShowOptionsElement
  }

  interface ElementTagNameMap {
    'wv-create-modal': HTMLWvCreateModalElement;
    'wv-help-modal': HTMLWvHelpModalElement;
    'wv-loading-pane': HTMLWvLoadingPaneElement;
    'wv-options-modal': HTMLWvOptionsModalElement;
    'wv-pb-inspector': HTMLWvPbInspectorElement;
    'wv-pb-manager': HTMLWvPbManagerElement;
    'wv-pb-node-container': HTMLWvPbNodeContainerElement;
    'wv-pb-node': HTMLWvPbNodeElement;
    'wv-pb-tree-node': HTMLWvPbTreeNodeElement;
    'wv-pb-tree': HTMLWvPbTreeElement;
    'wv-show-help': HTMLWvShowHelpElement;
    'wv-show-options': HTMLWvShowOptionsElement;
  }


}
