/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';

import '@stencil/redux';


export namespace Components {

  interface WvDatasourceManage {
    'apiRootUrl': string;
    'datasourceId': string;
    'pageDatasourceId': string;
    'pageDatasourceName': string;
    'pageDatasourceParams': string;
    'show': boolean;
  }
  interface WvDatasourceManageAttributes extends StencilHTMLAttributes {
    'apiRootUrl'?: string;
    'datasourceId'?: string;
    'pageDatasourceId'?: string;
    'pageDatasourceName'?: string;
    'pageDatasourceParams'?: string;
    'show'?: boolean;
  }

  interface WvDatasourceParamForm {}
  interface WvDatasourceParamFormAttributes extends StencilHTMLAttributes {}

  interface WvDatasourceStep1 {}
  interface WvDatasourceStep1Attributes extends StencilHTMLAttributes {}

  interface WvDatasourceStep2 {}
  interface WvDatasourceStep2Attributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WvDatasourceManage': Components.WvDatasourceManage;
    'WvDatasourceParamForm': Components.WvDatasourceParamForm;
    'WvDatasourceStep1': Components.WvDatasourceStep1;
    'WvDatasourceStep2': Components.WvDatasourceStep2;
  }

  interface StencilIntrinsicElements {
    'wv-datasource-manage': Components.WvDatasourceManageAttributes;
    'wv-datasource-param-form': Components.WvDatasourceParamFormAttributes;
    'wv-datasource-step1': Components.WvDatasourceStep1Attributes;
    'wv-datasource-step2': Components.WvDatasourceStep2Attributes;
  }


  interface HTMLWvDatasourceManageElement extends Components.WvDatasourceManage, HTMLStencilElement {}
  var HTMLWvDatasourceManageElement: {
    prototype: HTMLWvDatasourceManageElement;
    new (): HTMLWvDatasourceManageElement;
  };

  interface HTMLWvDatasourceParamFormElement extends Components.WvDatasourceParamForm, HTMLStencilElement {}
  var HTMLWvDatasourceParamFormElement: {
    prototype: HTMLWvDatasourceParamFormElement;
    new (): HTMLWvDatasourceParamFormElement;
  };

  interface HTMLWvDatasourceStep1Element extends Components.WvDatasourceStep1, HTMLStencilElement {}
  var HTMLWvDatasourceStep1Element: {
    prototype: HTMLWvDatasourceStep1Element;
    new (): HTMLWvDatasourceStep1Element;
  };

  interface HTMLWvDatasourceStep2Element extends Components.WvDatasourceStep2, HTMLStencilElement {}
  var HTMLWvDatasourceStep2Element: {
    prototype: HTMLWvDatasourceStep2Element;
    new (): HTMLWvDatasourceStep2Element;
  };

  interface HTMLElementTagNameMap {
    'wv-datasource-manage': HTMLWvDatasourceManageElement
    'wv-datasource-param-form': HTMLWvDatasourceParamFormElement
    'wv-datasource-step1': HTMLWvDatasourceStep1Element
    'wv-datasource-step2': HTMLWvDatasourceStep2Element
  }

  interface ElementTagNameMap {
    'wv-datasource-manage': HTMLWvDatasourceManageElement;
    'wv-datasource-param-form': HTMLWvDatasourceParamFormElement;
    'wv-datasource-step1': HTMLWvDatasourceStep1Element;
    'wv-datasource-step2': HTMLWvDatasourceStep2Element;
  }


}
