/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface WvSitemapAreaModal {
    'area': Object;
    'submitResponse': Object;
  }
  interface WvSitemapAreaModalAttributes extends StencilHTMLAttributes {
    'area'?: Object;
    'onWvSitemapManagerAreaModalCloseEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerAreaSubmittedEvent'?: (event: CustomEvent) => void;
    'submitResponse'?: Object;
  }

  interface WvSitemapManagerArea {
    'area': Object;
  }
  interface WvSitemapManagerAreaAttributes extends StencilHTMLAttributes {
    'area'?: Object;
    'onWvSitemapManagerAreaDeleteEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerAreaManageEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerNodeDeleteEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerNodeManageEvent'?: (event: CustomEvent) => void;
  }

  interface WvSitemapManager {
    'apiRoot': string;
    'appId': string;
    'initData': string;
  }
  interface WvSitemapManagerAttributes extends StencilHTMLAttributes {
    'apiRoot'?: string;
    'appId'?: string;
    'initData'?: string;
  }

  interface WvSitemapNodeModal {
    'apiRoot': string;
    'appId': string;
    'nodeAuxData': Object;
    'nodeObj': Object;
    'nodePageDict': Object;
    'submitResponse': Object;
  }
  interface WvSitemapNodeModalAttributes extends StencilHTMLAttributes {
    'apiRoot'?: string;
    'appId'?: string;
    'nodeAuxData'?: Object;
    'nodeObj'?: Object;
    'nodePageDict'?: Object;
    'onWvSitemapManagerNodeAuxDataUpdateEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerNodeModalCloseEvent'?: (event: CustomEvent) => void;
    'onWvSitemapManagerNodeSubmittedEvent'?: (event: CustomEvent) => void;
    'submitResponse'?: Object;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WvSitemapAreaModal': Components.WvSitemapAreaModal;
    'WvSitemapManagerArea': Components.WvSitemapManagerArea;
    'WvSitemapManager': Components.WvSitemapManager;
    'WvSitemapNodeModal': Components.WvSitemapNodeModal;
  }

  interface StencilIntrinsicElements {
    'wv-sitemap-area-modal': Components.WvSitemapAreaModalAttributes;
    'wv-sitemap-manager-area': Components.WvSitemapManagerAreaAttributes;
    'wv-sitemap-manager': Components.WvSitemapManagerAttributes;
    'wv-sitemap-node-modal': Components.WvSitemapNodeModalAttributes;
  }


  interface HTMLWvSitemapAreaModalElement extends Components.WvSitemapAreaModal, HTMLStencilElement {}
  var HTMLWvSitemapAreaModalElement: {
    prototype: HTMLWvSitemapAreaModalElement;
    new (): HTMLWvSitemapAreaModalElement;
  };

  interface HTMLWvSitemapManagerAreaElement extends Components.WvSitemapManagerArea, HTMLStencilElement {}
  var HTMLWvSitemapManagerAreaElement: {
    prototype: HTMLWvSitemapManagerAreaElement;
    new (): HTMLWvSitemapManagerAreaElement;
  };

  interface HTMLWvSitemapManagerElement extends Components.WvSitemapManager, HTMLStencilElement {}
  var HTMLWvSitemapManagerElement: {
    prototype: HTMLWvSitemapManagerElement;
    new (): HTMLWvSitemapManagerElement;
  };

  interface HTMLWvSitemapNodeModalElement extends Components.WvSitemapNodeModal, HTMLStencilElement {}
  var HTMLWvSitemapNodeModalElement: {
    prototype: HTMLWvSitemapNodeModalElement;
    new (): HTMLWvSitemapNodeModalElement;
  };

  interface HTMLElementTagNameMap {
    'wv-sitemap-area-modal': HTMLWvSitemapAreaModalElement
    'wv-sitemap-manager-area': HTMLWvSitemapManagerAreaElement
    'wv-sitemap-manager': HTMLWvSitemapManagerElement
    'wv-sitemap-node-modal': HTMLWvSitemapNodeModalElement
  }

  interface ElementTagNameMap {
    'wv-sitemap-area-modal': HTMLWvSitemapAreaModalElement;
    'wv-sitemap-manager-area': HTMLWvSitemapManagerAreaElement;
    'wv-sitemap-manager': HTMLWvSitemapManagerElement;
    'wv-sitemap-node-modal': HTMLWvSitemapNodeModalElement;
  }


}
